[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nl2sql-sqlite"
version = "0.1.0"
description = "SQLite Adapter for NL2SQL"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "nl2sql-adapter-sdk",
    "nl2sql-adapter-sqlalchemy",
    "SQLAlchemy>=2.0"
]

[project.entry-points."nl2sql.adapters"]
sqlite = "nl2sql_sqlite.adapter:SqliteAdapter"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["nl2sql_sqlite*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
