[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nl2sql-adapter-sqlalchemy"
version = "0.1.0"
description = "Base SQLAlchemy Adapter for NL2SQL"
requires-python = ">=3.9"
dependencies = [
    "nl2sql-adapter-sdk",
    "SQLAlchemy>=2.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["nl2sql_sqlalchemy_adapter*"]
